"use client";

import { useMemo, useState, useEffect, useRef } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { Button } from '@/components/ui/button';
import { 
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import { 
  BookOpen, 
  Sparkles, 
  TrendingDown, 
  Globe, 
  Leaf, 
  Zap,
  ArrowUpRight,
  Clock,
  Lightbulb
} from 'lucide-react';
import { useUser, useFirestore } from '@/firebase';
import { getDocs } from 'firebase/firestore';
import Link from 'next/link';
import { buildUserCalculatorRecordsQuery } from '@/lib/firestore-queries';

const EDUCATIONAL_TOPICS = [
  {
    title: "Carbon Footprint Basics",
    desc: "Understand the core concepts of carbon footprints and why tracking is the first step toward environmental preservation.",
    content: "A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions. The average carbon footprint for a person in the United States is 16 tons, one of the highest rates in the world. Globally, the average is closer to 4 tons. To have the best chance of avoiding a 2℃ rise in global temperatures, the average global carbon footprint per year needs to drop to under 2 tons by 2050.",
    icon: Globe,
    category: "Essentials",
    readTime: "5 min"
  },
  {
    title: "The Science of Climate",
    desc: "A deep dive into the thermal dynamics of our atmosphere and the impact of greenhouse gas concentration.",
    content: "Greenhouse gases act like a blanket around Earth, trapping energy in the atmosphere and causing it to warm. This phenomenon is called the greenhouse effect and is natural and necessary to support life on Earth. However, the buildup of greenhouse gases is changing Earth's climate and resulting in dangerous effects to human health and ecosystems.",
    icon: TrendingDown,
    category: "Science",
    readTime: "8 min"
  },
  {
    title: "Sustainable Daily Life",
    desc: "Actionable micro-habits that lead to macro environmental shifts. Small changes, global impact.",
    content: "Sustainability is about more than just recycling. It involves reducing waste, conserving energy, and making conscious choices about the products we buy and the food we eat. Simple actions like using reusable bags, switching to LED bulbs, and reducing meat consumption can make a significant difference over time.",
    icon: Leaf,
    category: "Lifestyle",
    readTime: "4 min"
  },
  {
    title: "Renewable Transitions",
    desc: "How the world is shifting from fossil fuels to clean energy and what role you play in the grid.",
    content: "Renewable energy comes from sources that replenish themselves naturally over short periods. This includes solar, wind, hydro, and geothermal energy. Transitioning to these sources is crucial for reducing carbon emissions and ensuring a sustainable energy future for the planet.",
    icon: Zap,
    category: "Energy",
    readTime: "6 min"
  },
  {
    title: "The Zero-Waste Model",
    desc: "Techniques for eliminating personal waste and understanding the circular economy in modern society.",
    content: "The zero-waste approach encourages the redesign of resource life cycles so that all products are reused. The goal is for no trash to be sent to landfills, incinerators, or the ocean. This involves the 5 Rs: Refuse, Reduce, Reuse, Recycle, and Rot (compost).",
    icon: Globe,
    category: "Waste",
    readTime: "7 min"
  }
];

export default function KnowledgeHubPage() {
  const { user } = useUser();
  const db = useFirestore();
  const [selectedTopic, setSelectedTopic] = useState<any>(null);
  const [latestRecord, setLatestRecord] = useState<any>(null);
  const fetchedRef = useRef(false);

  useEffect(() => {
    async function fetchOneTime() {
      if (!db || !user || fetchedRef.current) return;
      
      fetchedRef.current = true;
      const q = buildUserCalculatorRecordsQuery(db, user.uid, { limitCount: 1 });
      const snap = await getDocs(q);
      
      if (!snap.empty) {
        setLatestRecord(snap.docs[0].data());
      }
    }
    fetchOneTime();
  }, [db, user]);

  return (
    <div className="max-w-6xl mx-auto py-12 px-4 sm:px-6 space-y-12 animate-fade-in">
      <header className="text-center space-y-3">
        <h1 className="text-4xl font-headline font-bold text-foreground tracking-tight">
          Knowledge Hub
        </h1>
        <p className="text-zinc-500 text-sm max-w-lg mx-auto">
          Expert guidance and personalized insights for your sustainability journey.
        </p>
      </header>

      <Tabs defaultValue="educational" className="w-full">
        <div className="flex justify-center mb-12">
          <TabsList className="bg-white border border-zinc-200 p-1 rounded-xl h-auto shadow-sm">
            <TabsTrigger 
              value="educational" 
              className="py-2.5 px-6 rounded-lg font-headline text-sm data-[state=active]:bg-primary data-[state=active]:text-primary-foreground font-bold transition-all"
            >
               <BookOpen className="mr-2 h-4 w-4" /> Educational Library
            </TabsTrigger>
            <TabsTrigger 
              value="personalized" 
              className="py-2.5 px-6 rounded-lg font-headline text-sm data-[state=active]:bg-primary data-[state=active]:text-primary-foreground font-bold transition-all"
            >
               <Sparkles className="mr-2 h-4 w-4" /> Personalized Impact
            </TabsTrigger>
          </TabsList>
        </div>

        <TabsContent value="educational" className="outline-none">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {EDUCATIONAL_TOPICS.map((topic, i) => (
              <Card key={i} className="bg-white border border-zinc-200 shadow-sm hover:shadow-md transition-all rounded-2xl overflow-hidden group">
                <CardHeader className="p-6 pb-4">
                  <div className="flex justify-between items-start mb-4">
                    <div className="p-2.5 bg-zinc-50 border border-zinc-100 rounded-xl">
                      <topic.icon className="h-5 w-5 text-primary" />
                    </div>
                    <div className="flex items-center gap-1.5 text-[10px] font-black uppercase tracking-widest text-zinc-400">
                      <Clock className="h-3 w-3" /> {topic.readTime}
                    </div>
                  </div>
                  <div className="space-y-1">
                    <p className="text-[10px] font-black uppercase tracking-widest text-primary/70">{topic.category}</p>
                    <CardTitle className="font-headline text-xl text-foreground group-hover:text-primary transition-colors">
                      {topic.title}
                    </CardTitle>
                  </div>
                </CardHeader>
                <CardContent className="p-6 pt-0 space-y-6">
                  <p className="text-zinc-600 text-sm leading-relaxed line-clamp-3">
                    {topic.desc}
                  </p>
                  <Button 
                    variant="outline" 
                    className="w-full h-11 border-zinc-200 text-sm font-bold rounded-xl hover:bg-zinc-50 hover:text-primary transition-all"
                    onClick={() => setSelectedTopic(topic)}
                  >
                    Read Article <ArrowUpRight className="h-4 w-4 ml-2" />
                  </Button>
                </CardContent>
              </Card>
            ))}
          </div>
        </TabsContent>

        <TabsContent value="personalized" className="outline-none">
          {latestRecord ? (
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
              <Card className="bg-white border border-zinc-200 shadow-sm rounded-2xl overflow-hidden h-fit">
                <CardHeader className="p-8 border-b border-zinc-100 bg-zinc-50/50">
                  <div className="flex items-center gap-3">
                    <TrendingDown className="h-5 w-5 text-primary" />
                    <CardTitle className="font-headline text-lg">Impact Breakdown</CardTitle>
                  </div>
                  <CardDescription className="text-[10px] font-bold uppercase tracking-widest mt-1">
                    Telemetry from {new Date(latestRecord.timestamp?.toDate ? latestRecord.timestamp.toDate() : latestRecord.timestamp).toLocaleDateString()}
                  </CardDescription>
                </CardHeader>
                <CardContent className="p-8 space-y-8">
                  <div className="text-center py-6 bg-zinc-50 rounded-2xl border border-zinc-100">
                    <p className="text-[10px] font-black uppercase tracking-widest text-zinc-500 mb-1">Latest Journey Emission</p>
                    <div className="flex items-baseline justify-center gap-2">
                      <span className="text-5xl font-headline font-bold text-foreground">{latestRecord.co2?.toFixed(1) || latestRecord.totalEmissions?.toFixed(1) || 0}</span>
                      <span className="text-sm font-bold text-zinc-500 uppercase">kgCO2e</span>
                    </div>
                    <p className="text-[10px] font-bold text-zinc-500 mt-2">
                      {latestRecord.start} to {latestRecord.destination}
                    </p>
                  </div>
                  
                  <div className="space-y-6">
                    <div className="space-y-2">
                      <div className="flex justify-between items-center">
                        <span className="text-xs font-bold uppercase tracking-widest text-zinc-500">Journey Distance</span>
                        <span className="text-xs font-bold text-primary">{latestRecord.distance} km</span>
                      </div>
                      <Progress value={Math.min(100, (latestRecord.distance / 100) * 100)} className="h-1.5 bg-zinc-100" />
                    </div>
                  </div>
                </CardContent>
              </Card>

              <div className="space-y-6">
                <Card className="bg-zinc-900 text-white rounded-2xl p-8 border-none relative overflow-hidden shadow-xl">
                  <div className="relative z-10 space-y-6">
                    <div className="flex items-center gap-3">
                      <Lightbulb className="h-5 w-5 text-primary" />
                      <h4 className="text-[9px] font-black uppercase tracking-widest text-primary">Strategic Insight</h4>
                    </div>
                    <p className="text-lg font-headline font-bold leading-relaxed text-zinc-100">
                      {latestRecord.mode === 'car' || latestRecord.mode === 'motorcycle' ? 
                        `Your last trip via ${latestRecord.mode} produced significant emissions. Switching to the metro for this specific route could have saved approximately 82% of that carbon impact.` :
                        `Using ${latestRecord.mode} was an excellent choice. You've avoided approximately 4.5kg of CO2 compared to a standard petrol vehicle for this specific distance.`
                      }
                    </p>
                  </div>
                  <Sparkles className="absolute -bottom-6 -right-6 h-32 w-32 text-primary opacity-10" />
                </Card>
              </div>
            </div>
          ) : (
            <Card className="bg-white border border-zinc-200 shadow-sm rounded-2xl text-center py-24">
              <CardContent className="space-y-8 max-w-sm mx-auto">
                <div className="w-16 h-16 bg-zinc-50 border border-zinc-100 rounded-2xl flex items-center justify-center mx-auto shadow-sm">
                  <Sparkles className="h-8 w-8 text-primary/40" />
                </div>
                <div className="space-y-2">
                  <h3 className="text-xl font-headline font-bold text-foreground">Insights Locked</h3>
                  <p className="text-zinc-600 text-sm leading-relaxed">
                    Complete your first carbon impact audit to unlock hyper-personalized analysis and reduction strategies.
                  </p>
                </div>
                <Link href="/calculator" className="block">
                  <Button className="w-full h-12 bg-primary text-primary-foreground font-bold rounded-xl shadow-lg shadow-primary/20 hover:scale-[1.02] transition-transform">
                    Start Impact Audit
                  </Button>
                </Link>
              </CardContent>
            </Card>
          )}
        </TabsContent>
      </Tabs>

      <Dialog open={!!selectedTopic} onOpenChange={() => setSelectedTopic(null)}>
        <DialogContent className="max-w-2xl bg-white rounded-[2rem] border-none shadow-2xl p-0 overflow-hidden">
          <div className="p-8 space-y-6">
            <DialogHeader>
              <Badge variant="outline" className="w-fit text-primary border-primary/20 mb-2 uppercase tracking-widest text-[10px] font-bold">
                {selectedTopic?.category} • {selectedTopic?.readTime}
              </Badge>
              <DialogTitle className="text-3xl font-headline font-bold text-foreground leading-tight">
                {selectedTopic?.title}
              </DialogTitle>
              <DialogDescription className="text-sm font-medium text-zinc-500 mt-2">
                Knowledge Base Article • Environmental Science
              </DialogDescription>
            </DialogHeader>
            <div className="prose prose-zinc max-w-none">
              <p className="text-zinc-700 leading-relaxed text-lg">
                {selectedTopic?.content}
              </p>
            </div>
            <DialogFooter className="pt-6">
              <Button onClick={() => setSelectedTopic(null)} className="bg-primary text-white rounded-xl font-bold px-8">
                Done Reading
              </Button>
            </DialogFooter>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
